# 路径配置 - 统一管理所有文件路径
paths:
  # 数据根目录（相对于项目根目录）
  data_root: "data"

  # 网格数据子目录
  mesh_dir: "mesh"

  # 其他数据子目录
  custom_dir: "custom"
  examples_dir: "examples"

  # 结果和输出目录
  results_dir: "results"
  logs_dir: "logs"
  models_dir: "models"

  # 缓存和临时目录
  cache_dir: ".cache"
  temp_dir: ".temp"

  # 工具目录
  tools_dir: "tools"

  # 配置文件目录
  config_dir: "config"

  # 默认的mesh文件名（用于演示）
  default_meshes:
    - "1"


# Default configuration for RL mesh generation
sac_agent:
  actor_lr: 0.0003
  critic_lr: 0.0003
  alpha_lr: 0.0003
  gamma: 0.99
  tau: 0.005
  hidden_dim: 128
  buffer_size: 1000000
  batch_size: 256
  start_training_steps: 1000

# 经验回放缓冲区配置
replay_buffer:
  # 缓冲区类型: "normal" 或 "prioritized"
  type: "normal"
  capacity: 1000000

  # 优先级经验回放(PER)参数 - 仅当type为"prioritized"时使用
  prioritized:
    alpha: 0.6          # 优先级指数，控制优先级的强度 (0=uniform, 1=full prioritization)
    beta_start: 0.4     # 重要性采样权重的初始值
    beta_frames: 100000 # beta从beta_start增长到1.0所需的帧数
    epsilon: 0.000001   # 小常数，防止优先级为0

environment:
  n: 2
  g: 3
  alpha: 2
  beta: 6
  max_steps: 1000
  upsilon: 1.0
  kappa: 4.0
  M_angle: 60.0

training:
  # 训练基本参数
  max_episodes: 1000
  max_steps_per_episode: 1000

  # 保存和日志参数
  save_dir: "results"
  save_frequency: 100         # 每多少个episode保存一次检查点
  log_frequency: 10           # 每多少个episode输出一次日志
  evaluation_frequency: 50    # 每多少个episode进行一次评估

  # 早停和收敛参数
  early_stopping_patience: 200  # 早停的patience（暂未实现）
  convergence_threshold: 0.01   # 收敛阈值（暂未实现）