# Enhanced Monitoring Configuration for RL-Mesh-Generation
# This file configures the comprehensive training monitoring and logging system

# Basic monitoring settings
monitoring:
  # Enable/disable different monitoring features
  enable_tensorboard: true
  enable_csv_logging: true
  enable_performance_profiling: true
  enable_system_monitoring: true
  enable_real_time_plotting: false

  # Logging frequencies
  log_episode_frequency: 1          # Log every N episodes
  log_step_frequency: 100           # Log training steps every N steps
  system_monitoring_frequency: 50   # Monitor system resources every N episodes
  checkpoint_frequency: 1000        # Save checkpoints every N episodes

  # Performance profiling
  profiling:
    enable_timing: true
    timing_log_interval: 100
    track_memory_usage: true
    track_gpu_usage: true

  # Real-time monitoring
  real_time:
    refresh_interval: 30            # Seconds between updates
    plot_window_size: 1000         # Episodes to show in real-time plots
    enable_notifications: false    # Email/desktop notifications (if configured)

# Logging output settings
logging:
  # Directory structure
  base_log_dir: "logs"
  experiment_subdir: true          # Create subdirectory for each experiment
  timestamp_in_dirname: true       # Add timestamp to directory names

  # File formats
  save_json_summary: true
  save_csv_data: true
  save_tensorboard_logs: true
  compress_old_logs: false         # Compress logs older than N days

  # Retention policy
  max_log_age_days: 30            # Delete logs older than N days (0 = never delete)
  max_log_size_gb: 10             # Maximum total log size in GB

# Visualization settings
visualization:
  # Plot settings
  default_figure_size: [15, 10]
  dpi: 300
  style: "seaborn"                # matplotlib style
  color_palette: "husl"           # seaborn color palette

  # Learning curve settings
  moving_average_window: 100
  show_confidence_intervals: true
  plot_raw_data: true
  plot_trend_lines: true

  # Dashboard settings
  dashboard_refresh_rate: 60      # Seconds
  dashboard_history_length: 5000  # Episodes to keep in memory

# Performance monitoring thresholds
performance_thresholds:
  # Training progress alerts
  reward_improvement_threshold: 0.1    # Minimum improvement to consider significant
  convergence_patience: 500           # Episodes without improvement before considering converged
  sample_efficiency_target: 0.8      # Target performance percentile for efficiency calculation

  # System resource alerts
  cpu_usage_warning: 90              # CPU usage percentage warning threshold
  memory_usage_warning: 90           # Memory usage percentage warning threshold
  gpu_memory_warning: 90             # GPU memory usage warning threshold
  disk_space_warning: 95             # Disk space usage warning threshold

  # Training time alerts
  episode_time_warning_multiplier: 3.0  # Warn if episode takes 3x longer than average
  training_stall_threshold: 3600     # Seconds without progress before stall warning

# Evaluation monitoring
evaluation:
  # Frequency and settings
  default_num_episodes: 5
  save_evaluation_videos: false
  track_mesh_quality_evolution: true

  # Performance tracking
  track_best_performance: true
  save_best_model_snapshots: true
  evaluation_improvement_threshold: 0.05

# Comparison and analysis
analysis:
  # Automatic comparison features
  auto_compare_with_baseline: false
  baseline_experiment_path: ""

  # Statistical analysis
  confidence_level: 0.95
  significance_test: "t_test"      # t_test, wilcoxon, mann_whitney
  effect_size_threshold: 0.5      # Minimum effect size to consider meaningful

  # Hyperparameter tracking
  track_hyperparameter_effects: true
  hyperparameter_sensitivity_analysis: false

# Export and reporting
reporting:
  # Automatic report generation
  generate_daily_reports: false
  generate_completion_report: true
  include_plots_in_reports: true
  report_format: "html"           # html, pdf, markdown

  # Export formats
  export_data_formats: ["csv", "json"]
  export_plots_formats: ["png", "pdf"]

  # Sharing and collaboration
  enable_remote_monitoring: false
  monitoring_server_port: 8080
  allow_external_access: false

# Notification settings (optional)
notifications:
  enable_email: false
  email_settings:
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    recipients: []

  enable_desktop: false
  desktop_settings:
    show_progress_updates: true
    show_milestone_alerts: true
    show_error_alerts: true

  # Slack integration (optional)
  enable_slack: false
  slack_settings:
    webhook_url: ""
    channel: "#training-updates"
    mention_users: []

# Advanced monitoring features
advanced:
  # Distributed training monitoring
  distributed_training: false
  node_monitoring: false

  # Custom metrics
  custom_metrics:
    enable: false
    metrics: []

  # Integration with external tools
  wandb_integration:
    enable: false
    project: "rl-mesh-generation"
    entity: ""
    tags: []

  mlflow_integration:
    enable: false
    tracking_uri: ""
    experiment_name: ""

# Debug and development settings
debug:
  verbose_logging: false
  save_debug_info: false
  profile_memory_usage: false
  enable_interactive_debugging: false
  log_level: "INFO"              # DEBUG, INFO, WARNING, ERROR

# Backup and recovery
backup:
  enable_automatic_backup: true
  backup_frequency: 24           # Hours between backups
  backup_location: "backups"
  max_backup_count: 10           # Maximum number of backups to keep
  backup_compression: true